const mangekyouConstant = {
  NEW_IMAGE: 'NEW_IMAGE',
  ADD_HISTORY: 'ADD_HISTORY',
  LOAD_HISTORY: 'LOAD_HISTORY',
  UPDATE_CURRENT_IMAGE: 'UPDATE_CURRENT_IMAGE',
  TRIGGER_SHOWING: 'TRIGGER_SHOWING',
};

export default mangekyouConstant;
