const mangekyouConstant = {
  NEW_IMAGE: 'NEW_IMAGE',
  ADD_HISTORY: 'ADD_HISTORY',
  LOAD_HISTORY: 'LOAD_HISTORY',
  UPDATE_PREVIEW: 'UPDATE_PREVIEW',
  TRIGGER_SHOWING: 'TRIGGER_SHOWING',
  SET_PROCESSING_STATE: 'SET_PROCESSING_STATE',
  TRIGGER_COMPUTE: 'TRIGGER_COMPUTE',
  LOADING_FILE: 'LOADING_FILE',
  COMPUTING: 'COMPUTING',
  IDLE: 'IDLE',
};

export default mangekyouConstant;
